name: Docker Compose CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ toJson(steps.changed-files.outputs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files_yaml_from_source_file: .github/changed_files.yaml
  test:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: >
        ! failure()
        && ! cancelled()
        && fromJson(needs.changes.outputs.all).src_all_modified_files
    strategy:
      matrix:
        BE_VERSION: [v3, v4]
        ELASTIC_OR_JOBS_ENABLED: ['', elastic_or_jobs]
        LDAP_ENABLED: ['', ldap]
        OIDC_ENABLED: ['', oidc]
        DEV: ['', dev]
        exclude:
          - BE_VERSION: ${{
                !fromJson(needs.changes.outputs.all).v3_all_modified_files
                && 'v3'
                || (
                  !fromJson(needs.changes.outputs.all).v4_all_modified_files
                  && 'v4'
                )
              }}
          - ELASTIC_OR_JOBS_ENABLED: ${{
                !fromJson(needs.changes.outputs.all).elastic_or_jobs_all_modified_files
                && 'elastic_or_jobs' || 'nothing'
              }}
          - LDAP_ENABLED: ${{
                !fromJson(needs.changes.outputs.all).ldap_all_modified_files
                && 'ldap' || 'nothing'
              }}
          - OIDC_ENABLED: ${{
                !fromJson(needs.changes.outputs.all).oidc_all_modified_files
                && 'oidc' || 'nothing'
              }}
          - DEV: ${{
                !fromJson(needs.changes.outputs.all).dev_all_modified_files
                && 'dev' || 'nothing'
              }}
    steps:
      - uses: actions/checkout@v4
      - name: Test compose.yaml
        run: |-
          export JOBS_ENABLED=${{ matrix.ELASTIC_OR_JOBS_ENABLED }}
          export ELASTIC_ENABLED=${{ matrix.ELASTIC_OR_JOBS_ENABLED }}
          export LDAP_ENABLED=${{ matrix.LDAP_ENABLED }}
          export OIDC_ENABLED=${{ matrix.OIDC_ENABLED }}
          export BE_VERSION=${{ matrix.BE_VERSION }}
          export DEV=${{ matrix.DEV }}
          export DEV_BBACKUP=${DEV}
          docker compose --profile '*' \
            -f compose.yaml ${DEV:+-f .github/compose.dev.test.yaml} \
            up --wait --wait-timeout 1200
